// GET_FILMS
export const GET_FILMS = "GET_FILMS"
export const GET_FILMS_OK = "GET_FILMS_OK"
export const GET_FILMS_FAIL = "GET_FILMS_FAIL"

// GET_FILMS_GENRE
export const GET_FILMS_GENRE = "GET_FILMS_GENRE"
export const GET_FILMS_GENRE_OK = "GET_FILMS_GENRE_OK"
export const GET_FILMS_GENRE_FAIL = "GET_FILMS_GENRE_FAIL"

//GET_DOCS
export const GET_DOC = "GET_DOC"
export const GET_DOC_OK = "GET_DOC_OK"
export const GET_DOC_FAIL = "GET_DOC_FAIL"

// GET_POPULAR_FILMS
export const GET_POPULAR_FILMS = "GET_FILMS"
export const GET_POPULAR_FILMS_OK = "GET_FILMS_OK"
export const GET_POPULAR_FILMS_FAIL = "GET_FILMS_FAIL"
