// GET_FILMS
export const GET_FILMS = "GET_FILMS"
export const GET_FILMS_OK = "GET_FILMS_OK"
export const GET_FILMS_FAIL = "GET_FILMS_FAIL"

// GET_POPULAR_FILMS
export const GET_POPULAR_FILMS = "GET_FILMS"
export const GET_POPULAR_FILMS_OK = "GET_FILMS_OK"
export const GET_POPULAR_FILMS_FAIL = "GET_FILMS_FAIL"