export const ADD_FAVOURITES = "ADD_FAVOURITES"
export const ADD_FAVOURITES_OK = "ADD_FAVOURITES_OK"
export const ADD_FAVOURITES_FAIL = "ADD_FAVOURITES_FAIL"

export const WATCH_LATER = "WATCH_LATER"
export const WATCH_LATER_OK = "WATCH_LATER_OK"
export const WATCH_LATER_FAIL = "WATCH_LATER_FAIL"
